spring:
  application:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'
---
spring:
  profiles: prd
  datasource:
    initialize: true
    url: jdbc:oracle:thin:@BDCORP_SAUDE-PRD.SULAMERICA.BR:1527/SAUDEP
    username: ENC(qDYHZHbC0+15ZAUzmZfic3w3H8EFCgIg)
    password: ENC(T18LWXrr1qRpxl4J18i0lg==)
    driver-class-name: oracle.jdbc.driver.OracleDriver
    continue-on-error: true
    validation-query: SELECT 1 FROM DUAL
    initial-size: 5
    max-active: 10
    max-idle: 5
    min-idle: 2
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
    org.springframework.ws.client.MessageTracing.received: DEBUG
    org.springframework.ws.client.MessageTracing.sent: DEBUG
    org.springframework.ws.server.MessageTracing.received: DEBUG
    org.springframework.ws.server.MessageTracing.sent: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
---
spring:
  profiles: hml 
  datasource:
    initialize: true
    url: jdbc:oracle:thin:@BD_SAUDEH_CORP.SULAMERICA.BR:1527/SAUDEH
    username: ENC(juLKWJemWG08XiKXB53YmW0yXemOlRin)
    password: ENC(RcPu67bbed3B+wHLekWfPQ==)
    driver-class-name: oracle.jdbc.driver.OracleDriver
    continue-on-error: true
    validation-query: SELECT 1 FROM DUAL
    initial-size: 5
    max-active: 10
    max-idle: 5
    min-idle: 2
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
    org.springframework.ws.client.MessageTracing.received: TRACE
    org.springframework.ws.client.MessageTracing.sent: TRACE
    org.springframework.ws.server.MessageTracing.received: TRACE
    org.springframework.ws.server.MessageTracing.sent: TRACE
    org.springframework.web.client.RestTemplate: DEBUG          
---
spring:
  profiles: dsv
  datasource:
    initialize: true
    url: jdbc:oracle:thin:@BD_SAUDEH_CORP.SULAMERICA.BR:1527/SAUDEH
    username: ENC(juLKWJemWG08XiKXB53YmW0yXemOlRin)
    password: ENC(RcPu67bbed3B+wHLekWfPQ==)
    driver-class-name: oracle.jdbc.driver.OracleDriver
    continue-on-error: true
    validation-query: SELECT 1 FROM DUAL
    initial-size: 5
    max-active: 10
    max-idle: 5
    min-idle: 2
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
    org.springframework.ws.client.MessageTracing.received: TRACE
    org.springframework.ws.client.MessageTracing.sent: TRACE
    org.springframework.ws.server.MessageTracing.received: TRACE
    org.springframework.ws.server.MessageTracing.sent: TRACE
    org.springframework.web.client.RestTemplate: DEBUG 
---
spring:
  jpa:
    hibernate: 
      ddl-auto: update
  profiles: local
  datasource:
    initialize: true
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: dataBaseTest
    password: dataBaseTest
    driver-class-name: oracle.jdbc.driver.OracleDriver
    continue-on-error: true
    validation-query: SELECT 1 FROM DUAL
    initial-size: 5
    max-active: 10
    max-idle: 5
    min-idle: 2
vigilante:
  url: https://ipvigilante.com/json/
localizacao:
  url: https://www.metaweather.com//api/location/search/?lattlong=
temperatura:
  url: https://www.metaweather.com/api/location/
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
    org.springframework.ws.client.MessageTracing.received: TRACE
    org.springframework.ws.client.MessageTracing.sent: TRACE
    org.springframework.ws.server.MessageTracing.received: TRACE
    org.springframework.ws.server.MessageTracing.sent: TRACE
    org.springframework.web.client.RestTemplate: DEBUG 